### PR TITLE
Slight cleanup to EnergyFarm parser

### PR DESCRIPTION
**Pull request by max-zilla**

### CODE REVIEW

**Comment by max-zilla** [comment]
@harshagrawal28 here is the PR. changes:
- add CheckMessage logic. Here I basically check to see if the trigger file is one I care about - does it start with "Weather" and have CEN/SE/NE in filename? If not, we don't care about it.
- replaced all the geostreams functions in the extractor with the pyclowder2 version. these are somewhat new to PyClowder2, but best to use these so we don't have to update extractor if the API changes. Slight changes to code to support this.
- update extractor info. put myself as author so i can be the contact for external people if necessary but included you as well.

Otherwise this looks good. Will merge and prepare to deploy.

**Comment by harshagrawal28** [comment]
The default Sensor Name in terra_met_datparser.py is AZMET Maricopa Weather Station. Shouldn't it be UIUC Energy Farm?
Also, I think the extractor should only be triggered on files with Weather(SE/CEN/NE)_AvgYY.dat (WeatherSE_Avg15.dat) and not WeatherSE_DayAvg.dat (DayAvg files). @dlebauer could you confirm this?

**Comment by max-zilla** [comment]
@harshagrawal28 the AZMET weather station was a change on the original datparser extractor, I just changed it at the same time. Yours is the UIUC Energy Farm - CEN for example.

**Comment by dlebauer** [comment]
Yes we want the 15min data and can ignore the daily summary files

**Pull request merged**
